export enum ClientHeaders {
  Ping,
  Authenticate,
  Register,
  DeleteAccount,
  RecoverAccount,
  ListCharacters,
  CreateCharacter,
  DeleteCharacter,
  SelectCharacter,
  SellCharacter,
  BuyCharacter,
  CharactersForSale,
  ConfirmCharacterPurchase,
}
