export enum ServerHeaders {
  Pong,
  Alert,
  AuthenticationSuccess,
  RegistrationSuccess,
  AccountDeleted,
  AccountRecovery,
  UserCharacterList,
  CharacterCreated,
  CharacterDeleted,
  CharacterSelected,
  CharacterSold,
  CharacterBought,
  AvailableCharactersForSale,
  PurchaseConfirmation,
}
